from enum import StrEnum


class WordAction(StrEnum):
    NONE = "NONE"
    CHARACTER_APPENDED = "CHARACTER_APPENDED"
    PENDING_SELECTION_CREATED = "PENDING_SELECTION_CREATED"
    PENDING_SELECTION_RESOLVED = "PENDING_SELECTION_RESOLVED"
    PENDING_SELECTION_CANCELLED = "PENDING_SELECTION_CANCELLED"
    CHARACTER_REMOVED = "CHARACTER_REMOVED"
    WORD_CLEARED = "WORD_CLEARED"
    WORD_CONFIRMED = "WORD_CONFIRMED"
    WHOLE_WORD_COMMITTED = "WHOLE_WORD_COMMITTED"
    WHOLE_WORD_COMMIT_REJECTED = "WHOLE_WORD_COMMIT_REJECTED"
    DUPLICATE_IGNORED = "DUPLICATE_IGNORED"
    LIMIT_REACHED = "LIMIT_REACHED"
    ERROR = "ERROR"
